=== MyzBai/TinkerersSubject/public/gconfig/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [ "skills", "enemies" ],
    "properties": {
        "enemies": {
            "type": "object",
            "required": [ "enemyList" ],
            "properties": {
                "enemyList": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    }
                }
            }
        },
        "player": {
            "type": "object",
            "properties": {
                "modList": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/mod" }
                }
            }
        },
        "skills": {
            "type": "object",
            "required": [ "skillList" ],
            "properties": {
                "skillList": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [ "name", "attackSpeed", "manaCost", "baseDamageMultiplier", "levelReq" ],
                        "properties": {
                            "name": { "type": "string" },
                            "levelReq": { "type": "integer", "minimum": 1, "default": 1, "description": "Required player level\nNote - At least one skill must have a value of 1" },
                            "attackSpeed": { "type": "number", "minimum": 0.001, "maximum": 10, "default": 1, "description": "Number of attacks per second" },
                            "manaCost": { "type": "integer", "minimum": 0 },
                            "baseDamageMultiplier": { "type": "integer", "minimum": 1, "default": 100, "description": "A multiplier used to balance the skill. A value of 100 is 100% of base damage." },
                            "mods": {
                                "type": "array",
                                "items": { "$ref": "#/definitions/mod" }
                            }
                        }
                    }
                }
            }
        },
        "items": {
            "type": "object",
            "required": [ "itemList", "craftList", "modTables" ],
            "properties": {
                "itemList": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": { "type": "string" },
                            "levelReq": { "type": "integer", "minimum": 0 }
                        }
                    }
                },
                "craftList": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "required": [ "id", "levelReq", "cost" ],
                        "properties": {
                            "id": {
                                "enum": [
                                    "reforge", "reforgeIncludePhysical", "reforgeIncludeCritical", "reforgeIncludeMana", "reforgeHigherChanceSameMods", "reforgeLowerChanceSameMods",
                                    "addRandom", "addPhysical", "addCritical", "addMana",
                                    "removeRandom", "removePhysical", "removeCritical", "removeMana",
                                    "removeRandomAddPhysical", "removeRandomAddCritical", "removeRandomAddMana" ]
                            },
                            "levelReq": { "type": "integer", "minimum": 0 },
                            "cost": { "type": "integer", "minimum": 0 }
                        }
                    }
                },
                "modTables": {
                    "type": "object",
                    "required": [ "general" ],
                    "properties": {
                        "general": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "required": [ "weight", "levelReq", "mod" ],
                                    "properties": {
                                        "weight": { "type": "integer", "minimum": 0 },
                                        "levelReq": { "type": "integer", "minimum": 0 },
                                        "mod": { "$ref": "#/definitions/mod" }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "achievements": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [ "description" ],
                        "properties": {
                            "description": {
                                "type": "string",
                                "anyOf": [
                                    { "enum": [ "Reach Level {#}" ] }, { "pattern": "^Reach Level \\{\\d+\\}$" },
                                    { "enum": [ "Prestige {#}" ] }, { "pattern": "^Prestige \\{\\d+?\\}$" },
                                    { "enum": [ "Deal Damage {#}", "Deal Physical Damage {#}" ] }, { "pattern": "^Deal( Physical| Elemental)? Damage \\{\\d+\\}$" },
                                    { "enum": [ "Generate Gold {#}" ] }, { "pattern": "^Generate Gold \\{\\d+\\}$" },
                                    { "enum": [ "Regenerate Mana {#}" ] }, { "pattern": "^Regenerate Mana \\{\\d+\\}$" },
                                    { "enum": [ "Perform Hits {#}" ] }, { "pattern": "^Perform Hits \\{\\d+\\}$" },
                                    { "enum": [ "Perform Critical Hits {#} Total Critical Hits" ] }, { "pattern": "^Perform Critical Hits \\{\\d+\\}$" }
                                ]
                            },
                            "modList": {
                                "type": "array",
                                "description": "Each mod will be applied upon completing the achievement",
                                "items": {
                                    "$ref": "#/definitions/mod"
                                }
                            }
                        }
                    }
                }
            }
        },
        "prestige": {
            "type": "object",
            "required": [ "goldMultiplier" ],
            "properties": {
                "goldMultiplier": { "type": "integer", "default": 20, "description": "Each prestige will apply this multiplier to gold per second" }
            }
        }
    },
    "definitions": {
        "mod": {
            "type": "string",
            "oneOf": [
                { "enum": [ "Adds {#} To {#} Physical Damage" ] }, { "pattern": "^Adds \\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\} To \\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\} Physical Damage$" },
                { "enum": [ "{#}% Increased Physical Damage" ] }, { "pattern": "^\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% Increased Physical Damage$" },
                { "enum": [ "{#}% More Physical Damage" ] }, { "pattern": "^\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% More Physical Damage$" },
                { "enum": [ "{#}% More Damage" ] }, { "pattern": "^\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% More Damage Damage$" },
                { "enum": [ "+{#}% Hit Chance" ] }, { "pattern": "^\\+\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% Hit Chance$" },
                { "enum": [ "{#}% Increased Attack Speed" ] }, { "pattern": "^\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% Increased Attack Speed$" },
                { "enum": [ "+{#}% Critical Hit Chance" ] }, { "pattern": "^\\+\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% Critical Hit Chance$" },
                { "enum": [ "+{#}% Critical Hit Multiplier" ] }, { "pattern": "^\\+\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% Critical Hit Multiplier$" },
                { "enum": [ "+{#} Maximum Mana" ] }, { "pattern": "^\\+\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\} Maximum Mana$" },
                { "enum": [ "+{#}% Increased Maximum Mana" ] }, { "pattern": "^\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\}% Increased Maximum Mana$" },
                { "enum": [ "+{#} Mana Regeneration" ] }, { "pattern": "^\\+\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\} Mana Regeneration$" },
                { "enum": [ "+{#} Gold Per Second" ] }, { "pattern": "^\\+\\{(\\d+(\\.\\d+)?)(-\\d+(\\.\\d+)?)?\\} Gold Per Second$" }
            ]
        }
    }
}

=== MyzBai/TinkerersSubject/public/gconfig/demo.json
{
    "$schema": "./schema.json",
    "enemies": {
        "enemyList": [ 100, 300, 800, 2000, 5000, 10000, 30000, 50000, 100000, 200000 ]
    },
    "player": {
        "modList": [
            "Adds {1} To {3} Physical Damage",
            "+{100} Maximum Mana",
            "+{1} Mana Regeneration",
            "+{1} Gold Per Second",
            "+{150}% Critical Hit Multiplier"
        ]
    },
    "skills": {
        "skillList": [
            {
                "name": "Default Attack",
                "levelReq": 1,
                "attackSpeed": 1,
                "manaCost": 1,
                "baseDamageMultiplier": 100,
                "mods": [ "+{100}% Hit Chance" ]
            },
            {
                "name": "Super Attack",
                "levelReq": 2,
                "attackSpeed": 0.65,
                "manaCost": 3,
                "baseDamageMultiplier": 250,
                "mods": [
                    "+{80}% Hit Chance"
                ]
            },
            {
                "name": "Critical Attack",
                "levelReq": 3,
                "attackSpeed": 1.2,
                "manaCost": 5,
                "baseDamageMultiplier": 180,
                "mods": [
                    "+{60}% Hit Chance",
                    "+{20}% Critical Hit Chance",
                    "+{80}% Critical Hit Multiplier"
                ]
            }
        ]
    },
    "items": {
        "itemList": [
            { "name": "Item 1", "levelReq": 1 },
            { "name": "Item 2", "levelReq": 2 },
            { "name": "Item 3", "levelReq": 3 },
            { "name": "Item 4", "levelReq": 5 },
            { "name": "Item 5", "levelReq": 7 }
        ],
        "modTables": {
            "general": [
                [
                    { "weight": 10, "levelReq": 1, "mod": "+{1} Gold Per Second" },
                    { "weight": 5, "levelReq": 5, "mod": "+{2} Gold Per Second" }
                ],
                [
                    { "weight": 100, "levelReq": 1, "mod": "Adds {1} To {3} Physical Damage" },
                    { "weight": 100, "levelReq": 2, "mod": "Adds {3-4} To {4-6} Physical Damage" },
                    { "weight": 100, "levelReq": 5, "mod": "Adds {5-8} To {8-12} Physical Damage" }
                ],
                [
                    { "weight": 100, "levelReq": 1, "mod": "{30-40}% Increased Physical Damage" },
                    { "weight": 100, "levelReq": 3, "mod": "{40-60}% Increased Physical Damage" },
                    { "weight": 100, "levelReq": 5, "mod": "{80-100}% Increased Physical Damage" }
                ],
                [
                    { "weight": 100, "levelReq": 1, "mod": "+{5}% Hit Chance" },
                    { "weight": 100, "levelReq": 2, "mod": "+{6-8}% Hit Chance" },
                    { "weight": 100, "levelReq": 3, "mod": "+{9-12}% Hit Chance" },
                    { "weight": 100, "levelReq": 5, "mod": "+{13-15}% Hit Chance" },
                    { "weight": 100, "levelReq": 7, "mod": "+{16-20}% Hit Chance" }
                ],
                [
                    { "weight": 30, "levelReq": 1, "mod": "{5-10}% Increased Attack Speed" },
                    { "weight": 30, "levelReq": 3, "mod": "{10-15}% Increased Attack Speed" }
                ],
                [
                    { "weight": 70, "levelReq": 1, "mod": "+{10}% Critical Hit Chance" },
                    { "weight": 70, "levelReq": 2, "mod": "+{20}% Critical Hit Chance" },
                    { "weight": 70, "levelReq": 5, "mod": "+{30}% Critical Hit Chance" }
                ],
                [
                    { "weight": 60, "levelReq": 1, "mod": "+{20}% Critical Hit Multiplier" },
                    { "weight": 60, "levelReq": 3, "mod": "+{30}% Critical Hit Multiplier" },
                    { "weight": 60, "levelReq": 5, "mod": "+{50}% Critical Hit Multiplier" }
                ],
                [
                    { "weight": 100, "levelReq": 1, "mod": "+{10-20} Maximum Mana" },
                    { "weight": 100, "levelReq": 2, "mod": "+{21-30} Maximum Mana" },
                    { "weight": 100, "levelReq": 3, "mod": "+{31-40} Maximum Mana" },
                    { "weight": 100, "levelReq": 5, "mod": "+{41-50} Maximum Mana" }
                ],
                [
                    { "weight": 100, "levelReq": 1, "mod": "{20-30}% Increased Maximum Mana" },
                    { "weight": 100, "levelReq": 3, "mod": "{30-40}% Increased Maximum Mana" },
                    { "weight": 100, "levelReq": 5, "mod": "{40-50}% Increased Maximum Mana" }
                ],
                [
                    { "weight": 100, "levelReq": 1, "mod": "+{1} Mana Regeneration" },
                    { "weight": 100, "levelReq": 3, "mod": "+{2} Mana Regeneration" }
                ]
            ]
        },
        "craftList": [
            { "id": "reforge", "cost": 10, "levelReq": 1 },
            { "id": "reforgeIncludePhysical", "cost": 100, "levelReq": 1 },
            { "id": "reforgeIncludeCritical", "cost": 100, "levelReq": 1 },
            { "id": "reforgeIncludeMana", "cost": 100, "levelReq": 1 },

            { "id": "addRandom", "cost": 200, "levelReq": 1 },
            { "id": "addPhysical", "cost": 200, "levelReq": 1 },
            { "id": "addCritical", "cost": 200, "levelReq": 1 },
            { "id": "addMana", "cost": 200, "levelReq": 1 },

            { "id": "removeRandom", "cost": 200, "levelReq": 1 },

            { "id": "removeRandomAddPhysical", "cost": 500, "levelReq": 1 },
            { "id": "removeRandomAddCritical", "cost": 500, "levelReq": 1 },
            { "id": "removeRandomAddMana", "cost": 500, "levelReq": 1 }
        ]
    },
    "achievements": {
        "list": [
            { "description": "Reach Level {10}" },
            { "description": "Deal Physical Damage {10000}", "modList": [ "{10}% More Physical Damage" ] },
            { "description": "Generate Gold {5000}", "modList": [ "+{1} Gold Per Second" ] },
            { "description": "Perform Hits {1000}", "modList": [ "+{5}% Hit Chance" ] },
            { "description": "Perform Critical Hits {1000}", "modList": [ "+{5}% Critical Hit Chance" ] },
            { "description": "Regenerate Mana {1000}", "modList": [ "+{1} Mana Regeneration" ] }
        ]
    }

}
