=== MyzBai/TinkerersSubject/public/gconfig/schemas/gameConfig.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "schemas/gconfig/gameConfig.schema.json",
    "required": ["enemies"],
    "type": "object",
    "properties": {
        "options": {
            "$ref": "definitions/options.schema.json#/definitions/options"
        },
        "enemies": {
            "$ref": "definitions/enemies.schema.json#/definitions/enemies"
        },
        "player": {
            "$ref": "definitions/player.schema.json#/definitions/player"
        },
        "components": {
            "$ref": "definitions/components/components.schema.json#/definitions/components"
        }
    }
}

=== MyzBai/TinkerersSubject/public/gconfig/configs/demo.json
{
    "$schema": "../schemas/gameConfig.schema.json",
    "options": {
        "endPrompt": {
            "body": "The game is in early stages and your feedback would be highly appreciated. \nPlease check out the links down in the footer. \nThank you for playing.",
            "footer": "Note: You can create your own configuration. Header over to github to find out more!",
            "title": "You completed the Demo!"
        }
    },
    "enemies": {
        "enemyList": [
            200,
            1000,
            10000,
            25000,
            100000,
            300000,
            800000,
            2000000,
            10000000
        ]
    },
    "player": {
        "modList": [
            "Adds {1} To {3} Physical Damage",
            "+{100} Maximum Mana",
            "+{1} Mana Regeneration",
            "+{1} Gold Generation",
            "+{150}% Critical Hit Multiplier",
            "{5} Bleed Duration",
            "+{5} Maximum Bleed Stack",
            "{10} Burn Duration",
            "+{1} Maximum Burn Stack",
            "+{1} Maximum Minions"
        ]
    },
    "components": {
        "skills": {
            "attackSkills": {
                "skillList": [
                    {
                        "name": "Default Attack",
                        "attackSpeed": 1,
                        "baseDamageMultiplier": 100,
                        "levelReq": 1,
                        "manaCost": 1,
                        "goldCost": 0,
                        "mods": [
                            "+{100}% Hit Chance"
                        ]
                    },
                    [
                        {
                            "name": "Physical Attack",
                            "attackSpeed": 0.6,
                            "baseDamageMultiplier": 150,
                            "levelReq": 2,
                            "manaCost": 3,
                            "goldCost": 100,
                            "mods": [
                                "+{80}% Hit Chance",
                                "{50}% More Physical Damage"
                            ]
                        },
                        {
                            "name": "Physical Attack II",
                            "attackSpeed": 0.65,
                            "baseDamageMultiplier": 160,
                            "manaCost": 4,
                            "goldCost": 200,
                            "mods": [
                                "+{70}% Hit Chance",
                                "{80}% More Physical Damage"
                            ]
                        },
                        {
                            "name": "Physical Attack III",
                            "attackSpeed": 0.7,
                            "baseDamageMultiplier": 180,
                            "manaCost": 5,
                            "goldCost": 500,
                            "mods": [
                                "+{65}% Hit Chance",
                                "{100}% More Physical Damage"
                            ]
                        },
                        {
                            "name": "Physical Attack IV",
                            "attackSpeed": 0.75,
                            "baseDamageMultiplier": 200,
                            "manaCost": 8,
                            "goldCost": 1000,
                            "mods": [
                                "+{60}% Hit Chance",
                                "{150}% More Physical Damage"
                            ]
                        }
                    ],
                    [
                        {
                            "name": "Elemental Attack",
                            "attackSpeed": 0.6,
                            "baseDamageMultiplier": 150,
                            "levelReq": 2,
                            "manaCost": 3,
                            "goldCost": 100,
                            "mods": [
                                "+{80}% Hit Chance",
                                "{50}% More Elemental Damage"
                            ]
                        },
                        {
                            "name": "Elemental Attack II",
                            "attackSpeed": 0.65,
                            "baseDamageMultiplier": 160,
                            "manaCost": 4,
                            "goldCost": 200,
                            "mods": [
                                "+{70}% Hit Chance",
                                "{80}% More Elemental Damage"
                            ]
                        },
                        {
                            "name": "Elemental Attack III",
                            "attackSpeed": 0.7,
                            "baseDamageMultiplier": 180,
                            "manaCost": 5,
                            "goldCost": 500,
                            "mods": [
                                "+{65}% Hit Chance",
                                "{100}% More Elemental Damage"
                            ]
                        },
                        {
                            "name": "Elemental Attack IV",
                            "attackSpeed": 0.75,
                            "baseDamageMultiplier": 200,
                            "manaCost": 8,
                            "goldCost": 1000,
                            "mods": [
                                "+{60}% Hit Chance",
                                "{150}% More Elemental Damage"
                            ]
                        }
                    ],
                    [
                        {
                            "name": "Bleed Attack",
                            "attackSpeed": 0.35,
                            "baseDamageMultiplier": 300,
                            "levelReq": 3,
                            "manaCost": 10,
                            "goldCost": 100,
                            "mods": [
                                "+{60}% Hit Chance",
                                "+{20}% Chance To Bleed",
                                "{50}% More Bleed Damage"
                            ]
                        },
                        {
                            "name": "Bleed Attack II",
                            "attackSpeed": 0.4,
                            "baseDamageMultiplier": 225,
                            "manaCost": 11,
                            "goldCost": 200,
                            "mods": [
                                "+{60}% Hit Chance",
                                "+{25}% Chance To Bleed",
                                "{80}% More Bleed Damage"
                            ]
                        },
                        {
                            "name": "Bleed Attack III",
                            "attackSpeed": 0.4,
                            "baseDamageMultiplier": 250,
                            "manaCost": 12,
                            "goldCost": 500,
                            "mods": [
                                "+{55}% Hit Chance",
                                "+{30}% Chance To Bleed",
                                "{120}% More Bleed Damage"
                            ]
                        },
                        {
                            "name": "Bleed Attack IV",
                            "attackSpeed": 0.4,
                            "baseDamageMultiplier": 275,
                            "manaCost": 13,
                            "goldCost": 1000,
                            "mods": [
                                "+{50}% Hit Chance",
                                "+{40}% Chance To Bleed",
                                "{150}% More Bleed Damage"
                            ]
                        }
                    ],
                    [
                        {
                            "name": "Burn Attack",
                            "attackSpeed": 0.2,
                            "baseDamageMultiplier": 400,
                            "levelReq": 3,
                            "manaCost": 15,
                            "goldCost": 100,
                            "mods": [
                                "+{50}% Hit Chance",
                                "+{50}% Chance To Burn",
                                "{80}% More Burn Damage"
                            ]
                        },
                        {
                            "name": "Burn Attack II",
                            "attackSpeed": 0.2,
                            "baseDamageMultiplier": 430,
                            "manaCost": 17,
                            "goldCost": 200,
                            "mods": [
                                "+{50}% Hit Chance",
                                "+{50}% Chance To Burn",
                                "{120}% More Burn Damage"
                            ]
                        },
                        {
                            "name": "Burn Attack III",
                            "attackSpeed": 0.2,
                            "baseDamageMultiplier": 450,
                            "manaCost": 18,
                            "goldCost": 500,
                            "mods": [
                                "+{50}% Hit Chance",
                                "+{50}% Chance To Burn",
                                "{150}% More Burn Damage"
                            ]
                        },
                        {
                            "name": "Burn Attack IV",
                            "attackSpeed": 0.2,
                            "baseDamageMultiplier": 480,
                            "manaCost": 20,
                            "goldCost": 1000,
                            "mods": [
                                "+{50}% Hit Chance",
